### PR TITLE
HEL-349 | Use Red Hat UBI Python image in Docker

### PR DESCRIPTION
**Pull request by karisal-anders**
### feat(docker): use red hat ubi9 python image, add .dockerignore file

also remove deprecated version number from docker-compose.yml:
"the attribute `version` is obsolete, it will be ignored, please remove
it to avoid potential confusion"

refs HEL-349

## Tickets

[HEL-349](https://helsinkisolutionoffice.atlassian.net/browse/HEL-349)

[HEL-349]: https://helsinkisolutionoffice.atlassian.net/browse/HEL-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Kuvaselaamo branch is deployed to platta: https://kuvaselaamo-pr329.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Kuvaselaamo branch is deployed to platta: https://kuvaselaamo-pr329.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Kuvaselaamo branch is deployed to platta: https://kuvaselaamo-pr329.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Kuvaselaamo branch is deployed to platta: https://kuvaselaamo-pr329.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Kuvaselaamo branch is deployed to platta: https://kuvaselaamo-pr329.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Kuvaselaamo branch is deployed to platta: https://kuvaselaamo-pr329.dev.hel.ninja** :rocket::rocket::rocket:

**Review by melniiv — APPROVED** [review]

**Pull request merged**
