### PR TITLE
fix: link labels short translations

### PR DESCRIPTION
**Pull request by melniiv**

### CODE REVIEW

**Review by karisal-anders — APPROVED** [review]
If you're removing the translations, you could remove the "PDM label" translations as well. And I'm not sure if the capitalization of `Domain` in "Public domain" is necessary, but that's how PO described it in the ticket, so that would be safest to go with, or you can ask him if makes any kind of a difference to him whether it reads "Public domain" or "Public Domain".

**Comment by terovirtanen** [comment]
**Kuvaselaamo branch is deployed to platta: https://kuvaselaamo-pr334.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Kuvaselaamo branch is deployed to platta: https://kuvaselaamo-pr334.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Kuvaselaamo branch is deployed to platta: https://kuvaselaamo-pr334.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
